// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbfsLEq_UptEkgLNPAzje2Z5L9UVaM4L0',
    appId: '1:463964373649:web:d84e78a35c9218e693b530',
    messagingSenderId: '463964373649',
    projectId: 'accountable-flutter',
    authDomain: 'accountable-flutter.firebaseapp.com',
    storageBucket: 'accountable-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxjxPO4MeeTm_fvxKc2tNOLLj9kugC1KQ',
    appId: '1:463964373649:android:84f1ccf031eb8c5893b530',
    messagingSenderId: '463964373649',
    projectId: 'accountable-flutter',
    storageBucket: 'accountable-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk2U7oaH7nTNceHtaFf_lbjb956j42go4',
    appId: '1:463964373649:ios:7557b2ea820df23e93b530',
    messagingSenderId: '463964373649',
    projectId: 'accountable-flutter',
    storageBucket: 'accountable-flutter.appspot.com',
    iosBundleId: 'com.technoclever.accountableEnduserFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk2U7oaH7nTNceHtaFf_lbjb956j42go4',
    appId: '1:463964373649:ios:b701077e9761150f93b530',
    messagingSenderId: '463964373649',
    projectId: 'accountable-flutter',
    storageBucket: 'accountable-flutter.appspot.com',
    iosBundleId: 'com.technoclever.accountableEnduserFlutter.RunnerTests',
  );
}
